fixup

diff --git a/atlas b/atlas
--- a/atlas
+++ b/atlas
@@ -79,21 +79,21 @@ parse() {
 usage() {
 cat<<'GETOPTIONSHERE'
 Atlas is a CLI tool that has essentially one command: `atlas pull`
- 
+
 Atlas defaults to using a configuration file named `atlas.yml` placed
 in the root directory. Configuration file:
- 
+
 pull:
   branch: <branch-name>
   directory <directory-name>
   repository: <organization-name>/<repository-name>
- 
+
 Atlas can also use a configuration file in a different path using the `--config` flag
 after `atlas`: `atlas pull --config config.yml`.
- 
+
 Atlas can also be used without a configuration file by using the flags below after
 `atlas pull`.
- 
+
 `-b` or `--branch`
 `-r` or `--repository`
 `-d` or `--directory`
@@ -101,7 +101,7 @@ Atlas can also be used without a configuration file by using the flags below aft
 
 Commands:
   pull      pull
-  -h, --help                  
+  -h, --help
 GETOPTIONSHERE
 }
 # Generated by getoptions (END)
@@ -193,7 +193,7 @@ parse_pull() {
 }
 usage_pull() {
 cat<<'GETOPTIONSHERE'
-Usage: atlas pull [options...] [directories...]
+Usage: atlas pull [options...] [directory mappings...]
 Options:
       --config CONFIG         path to alternative atlas.yaml configuration file
   -b, --branch BRANCH         A branch of translation files
@@ -201,7 +201,7 @@ Options:
   -f, --filter FILTER         List of patterns to select which files and sub-directories to checkout.
   -v, --verbose               verbose output to terminal
   -s, --silent                no output to terminal
-  -h, --help                  
+  -h, --help
 GETOPTIONSHERE
 }
 # Generated by getoptions (END)
@@ -248,9 +248,10 @@ set_pull_params() {
   fi
 
   # Override vars based on args
-  if [ "$DIRECTORY" ];
+  if [ $# -gt 0 ];
   then
-    pull_directory="$DIRECTORY"
+    # Due to sh/dash compatibility, arrays are not supported, therefore directories with spaces aren't supported.
+    pull_directory="$*"
   fi
 
   if [ "$REPOSITORY" ];
@@ -271,6 +272,12 @@ set_pull_params() {
   pull_filter="$(echo "$pull_filter" | tr ',' ' ')"  # Accept comma and/or space separated directories list
 }
 
+contains_substring() {
+  # Checks if $1 string contains $2.
+  printf '%s' "$1" | grep --fixed-strings --silent -e "$2"
+  return $?
+}
+
 display_pull_params() {
   # Output configured vars to user
   echo "Pulling translation files"
@@ -283,9 +290,10 @@ display_pull_params() {
 pull_translations() {
   if [ -z "$pull_directory" ];
   then
-      echo "Error: At least one DIRECTORY map is required as a positional argument:"
-      echo "  $ atlas pull DIRECTORY_FROM1:DIRECTORY_TO1 DIRECTORY_FROM2:DIRECTORY_TO2 ..."
-      exit 1
+      echo "Missing positional argument:" >&2
+      echo "  At least one DIRECTORY map is required as a positional argument:" >&2
+      echo "  $ atlas pull DIRECTORY_FROM1:DIRECTORY_TO1 DIRECTORY_FROM2:DIRECTORY_TO2 ..." >&2
+      return 1
   fi
 
   if [ -z "$SILENT" ];
@@ -376,7 +384,8 @@ pull_translations() {
     directory_from="./translations_TEMP/${directory_from}"
 
     # If no colon is provided then directory_to=. (aka working directory)
-    if [[ $directory_from_to =~ ":" ]]; then
+    if contains_substring "$directory_from_to" ":";
+    then
       directory_to="$(echo "${directory_from_to}" | cut -f2 -d ':')"
     else
       directory_to=.
@@ -388,7 +397,7 @@ pull_translations() {
       echo "Done."
       echo "Copying translations from \"${directory_from}\" to \"./${directory_to}\"..."
     fi
-    cp -r ${directory_from}/* "${directory_to}"/ || exit 1
+    cp -r "${directory_from}"/* "${directory_to}"/ || exit 1
   done
 
   # finished "Copying translations from <temp dir> to <dest dir>..." step
@@ -426,15 +435,14 @@ if [ $# -gt 0 ]; then
 		pull)
 			parse_pull "$@"
             eval "set -- $PULL_REST"
-            DIRECTORY="$@" # Make the arguments available to `set_pull_params`
-            set_pull_params
+            set_pull_params "$@" # Make the arguments available to `set_pull_params`
             if [ -z "$SILENT" ];
             then
               display_pull_params
             fi
             # allow mocking pull_translations
             __ begin_pull_translations_mock __
-            pull_translations
+            pull_translations || exit 1
             __ end_pull_translations_mock __
             ;;
 		--) # no subcommand, arguments only
