feat: dry-run

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,18 +13,30 @@ jobs:
       uses: actions/checkout@v3
       with:
         fetch-depth: 0
-    - name: semantic release
-      env:
-        GITHUB_TOKEN: ${{ github.token }}
+
+    - name: Dry run semantic release to determine next version
+      id: dry_run
       run: |
         # Run in dry-run mode to determine the next tag version and store it in semantic-release-next-version.txt
-        npx semantic-release@21.0.7 --dry-run | tee semantic-release-dry-run-output.txt
-        cat semantic-release-dry-run-output.txt \
-          | grep -o 'Skip v.* tag creation in dry-run mode' \
-          | sed -e 's/^Skip //' | sed -e 's/ tag creation in dry-run mode$//' \
-          | tee semantic-release-next-version.txt
+        npx semantic-release@21.0.7 --dry-run
 
-        echo "DEBUG: Next version is '$(cat semantic-release-next-version.txt)'"  # Debug version number
+    - name: Semantic release
+      env:
+        DRY_RUN_OUTPUT: ${{join(steps.dry_run.outputs.*, '\n')}}
+        GITHUB_TOKEN: ${{ github.token }}
+      run: |
+        NEXT_VERSION=$(
+          echo "$DRY_RUN_OUTPUT" | \
+            grep -o 'Skip v.* tag creation in dry-run mode' \
+            | sed -e 's/^Skip //' | sed -e 's/ tag creation in dry-run mode$//'
+        )
+
+        echo "DEBUG: Next version is '$NEXT_VERSION'"  # Debug version number
+
+        if [ -z "$NEXT_VERSION" ]; then
+          echo "ERROR: Could not determine next version from semantic-release dry-run output."
+          exit 1
+        fi
 
         # Hardcode the next tag version in the atlas script
         sed -i -e "s/_ATLAS_VERSION=.*/_ATLAS_VERSION=\"$(cat semantic-release-next-version.txt)\"  # Tagged by release.yml/" atlas
